### ISSUE TITLE
running sample corba corba naming service error

### ISSUE THREAD

**Issue by Goulustis** [uzh-rpg/eds-buildconf#13]
Thanks for the great work!

I'm having trouble running the provided example.

after doing:
``
source env.sh
cd bundles/eds
ruby scripts/slam/eds/run_eds_logs.rb --dataset=atrium --log_type=davis /tmp/atrium.log
``
I'm getting this error:
![image](https://user-images.githubusercontent.com/43025723/205761415-631432c4-97a0-4213-be91-e76893541526.png)

Can anyone have a look and see what I'm missing?

Thanks in advance!

**Comment by chenhy396** [comment]
There is a solution to the CORBA related errors in `Troubleshooting` from [README.md](https://github.com/uzh-rpg/eds-buildconf). You may try it.

**Comment by Goulustis** [comment]
Your suggestion works. Thanks!
