### ISSUE TITLE
Event Camera Biases

### ISSUE THREAD

**Issue by low5545** [uzh-rpg/eds-buildconf#14]
I would like to ask whether do you still recall what biases you used for the Prophesee PPS3MVCD event camera in the recordings? I would really appreciate if you could share the biases / bias file. Thanks!

**Comment by jhidalgocarrio** [comment]
Hi, thanks for your question.
Please see below the content of the bias file for the Gen 3 Prophesee camera (VGA resolution) used to record the [EDS dataset](https://rpg.ifi.uzh.ch/eds.html#dataset).

```
% subsystem_ID 2418019330
% system_ID 28
194        %   bias_diff_off             %   v    
414        %   bias_diff_on              %   v    
300        %   bias_diff                 %   v    
1480       %   bias_fo                   %   i    
1250       %   bias_pr                   %   i    
1500       %   bias_refr                 %   i    
1500       %   bias_hpf                  %   i    
```
