### ISSUE TITLE
which sequences exactly 

### ISSUE THREAD

**Issue by knelk** [uzh-rpg/eds-buildconf#15]
the rpg dataset (https://rpg.ifi.uzh.ch/ECCV18_stereo_davis.html), i.e. your reference [50], has 2 sequences for boxes, desk, monitor. 

did you use sequence 1 or sequence 2 in your Table 2&3?

Do you also have (non-published) results for sequences2?

Thanks!

**Comment by jhidalgocarrio** [comment]
Hi Simon,
Thanks for asking. We used sequence 2 for the boxes, desk, and monitor.

**Comment by knelk** [comment]
Thanks!
