### ISSUE TITLE
rb: cannot connect to X server

### ISSUE THREAD

**Issue by Yukun66** [uzh-rpg/eds-buildconf#6]
Great work! But when I am trying to run the docker image in my docker, there is an error: 

rb: cannot connect to X server

I'm following your execution steps, and the error occurs when I run: run_eds_log.rb
Any suggestions will help, Thank you!

**Comment by Yukun66** [comment]
Hi! it seems like I've solved it.
The way I open the docker is wrong without using X server to show GUI.
Thanks.

**Comment by jhidalgocarrio** [comment]
Hi, thanks for trying the docker
You need to create a docker container with X11 support. For example:
```
docker run -ti -P --privileged -v /dev/bus/usb:/dev/bus/usb \
    -v /dev/dri:/dev/dri:rw -v /tmp/.X11-unix:/tmp/.X11-unix -v /dev/video0:/dev/video0:rw -v /etc/localtime:/etc/localtime:ro --name eds\
    --env="DISPLAY" \
    --env="QT_X11_NO_MITSHM=1" -e DSUPPORT=1 jhidalgocarrio/eds:20.04
```

**Comment by fmfernandezext** [comment]
Hey! This solution is not working for me, do you have any other suggestions? 
Thanks!
