### ISSUE TITLE
Task configure error

### ISSUE THREAD

**Issue by huangfeng95** [uzh-rpg/eds-buildconf#8]
Hello, thank you for your project.
However, when I run `run_eds_logs.rb`, the following error is displayed:
![image](https://user-images.githubusercontent.com/19809051/178444187-59946358-46d9-4700-8faf-0b6ba02648b1.png)
How can I check the causes of local errors? Looking forward to your help.

**Comment by chenhy396** [comment]
> Hello, thank you for your project. However, when I run `run_eds_logs.rb`, the following error is displayed: ![image](https://user-images.githubusercontent.com/19809051/178444187-59946358-46d9-4700-8faf-0b6ba02648b1.png) How can I check the causes of local errors? Looking forward to your help.

Hi guy, I got the same error. Have you solved the problem? If so, could you share your solutions?

**Comment by huangfeng95** [comment]
> > Hello, thank you for your project. However, when I run `run_eds_logs.rb`, the following error is displayed: ![image](https://user-images.githubusercontent.com/19809051/178444187-59946358-46d9-4700-8faf-0b6ba02648b1.png) How can I check the causes of local errors? Looking forward to your help.
> 
> Hi guy, I got the same error. Have you solved the problem? If so, could you share your solutions?

I solved this problem by modifying the path of _config_file_ and _calib_file_ in Task file **eds::Task.yml** (under **bundles/eds/config**). I hope it could help you. @chenhy396

**Comment by chenhy396** [comment]
Thanks for your quick response. It did help by modifying the path. @huangfeng95
